### ISSUE TITLE
Always drop down

### ISSUE THREAD

**Issue by FluffyDiscord** [mskocik/svelecte#176]
Currently the select intelligently renders the dropdown list bellow or above is there is no space. I would like to force it always to render bellow.

**Comment by mskocik** [comment]
This is what you need: https://github.com/mskocik/svelecte/issues/38#issuecomment-943225826

**Comment by FluffyDiscord** [comment]
this might work for always up, but not for always down 
![image](https://github.com/mskocik/svelecte/assets/10332247/ee623f09-8ef5-475a-92e3-0b563a52767c)

**Comment by mskocik** [comment]
It works, but needs slightly different override:

```css
:global(.dropdown-down .sv-dropdown) {
  bottom: auto !important;
}
```
